Feature: Github actions

diff --git a/.github/workflows/workflow.yaml b/.github/workflows/workflow.yaml
--- a/.github/workflows/workflow.yaml
+++ b/.github/workflows/workflow.yaml
@@ -39,8 +39,16 @@ jobs:
           npm install
           npm install -g prisma
 
+      - name: Debug Information
+        run: |
+          echo "Checking MySQL Connection..."
+          nc -z -v -w5 mysql 3306 || echo "MySQL Connection Failed"
+          echo "Environment Variables:"
+          env
+          echo "End of Debug Information"
+
       - name: Prisma Generate
         run: npx prisma generate
 
-      - name: Run npm tests
+      - name: Run Tests
         run: npm run test
